INSERT INTO budgetitems VALUES(1,'Income','Work Income',4200.0,'Income',1);
INSERT INTO budgetitems VALUES(2,'Rent','Apartment Rent',205.0,'Housing',1);
INSERT INTO budgetitems VALUES(3,'EnBW','Electric and Gas',110.0,'Electric',1);
INSERT INTO budgetitems VALUES(4,'Phone','Telekom Mobilfunk',92.0,'Phone',20);
INSERT INTO budgetitems VALUES(5,'Internet','Telekom Festnetz',92.0,'Internet',20);
INSERT INTO budgetitems VALUES(7,'Train Ticket','Deutch Bahn VVS',46.54999999999999716,'Mobility',23);
INSERT INTO budgetitems VALUES(8,'USAA Loan','USAA',134.0,'Debt','Monthly',15);
INSERT INTO budgetitems VALUES(9,'USAA Renter''s Insurance','USAA',23.48000000000000042,'Insurance',15);
INSERT INTO budgetitems VALUES(10,'USAA Credit Card','USAA',250.0,'Credit',15);
INSERT INTO budgetitems VALUES(11,'CHASE Credit Card','CHASE',50.0,'Credit',15);
INSERT INTO budgetitems VALUES(12,'MILSTAR Credit Card','AAFES MILSTAR',200.0,'Credit',1);
INSERT INTO budgetitems VALUES(13,'Retirement','Military Retirement Income',1890.0,'Income',1);
INSERT INTO budgetitems VALUES(15,'Food','Groceries and Restaurants',500.0,'Food',1);
INSERT INTO budgetitems VALUES(16,'Entertainment','Entertainment',100.0,'Entertainment',1);
INSERT INTO budgetitems VALUES(17,'Other','Other',0.0,'Other',1);
INSERT INTO budgetitems VALUES(18,'Shopping','Shopping',100.0,'Shopping',1);
INSERT INTO budgetitems VALUES(19,'Child Support','Child Support',2017.0,'Child Support',1);
INSERT INTO budgetitems VALUES(20,'Storage Unit (USA)','Storage Unit in GA for Non-Temp Storage (Military)',46.75,'Bills',1);
